---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailbuddy
  labels:
    app: emailbuddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailbuddy
  template:
    metadata:
      name: emailbuddy
      labels:
        app: emailbuddy
    spec:
      containers:
        - name: emailbuddy
          image: registry.matheplus.ninja/emailbuddy/frontend:latest
---
apiVersion: v1
kind: Service
metadata:
  name: emailbuddy
spec:
  selector:
    app: emailbuddy
  ports:
    - port: 80 # Default port for image
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emailbuddy-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: emailbuddy.matheplus.ninja
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emailbuddy
            port:
              number: 80
  ingressClassName: public
  tls:
    - hosts:
      - emailbuddy.matheplus.ninja
      secretName: emailbuddy-ingress-certificate
